- name: Create SonarQube namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ sonarqube_namespace }}"
    state: present

- name: Add SonarQube Helm repo
  community.kubernetes.helm_repository:
    name: sonarqube
    repo_url: "{{ sonarqube_helm_repo }}"

- name: Deploy SonarQube
  community.kubernetes.helm:
    name: "{{ sonarqube_release_name }}"
    chart_ref: sonarqube/sonarqube
    chart_version: "{{ sonarqube_chart_version }}"
    release_namespace: "{{ sonarqube_namespace }}"
    values: "{{ sonarqube_values }}"
