---
- name: Configure AKS with DevOps tools (Helm-based)
  hosts: aks
  become: true
  tasks:
    - name: Install Helm on AKS
      shell: |
        curl https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz | tar -xz && mv linux-amd64/helm /usr/local/bin/helm
      when: ansible_os_family == "Linux"

    - name: Deploy Jenkins using Helm
      include_role:
        name: jenkins

    - name: Deploy SonarQube using Helm
      include_role:
        name: sonarqube

    - name: Deploy Clair using Helm
      include_role:
        name: clair

    - name: Deploy ELK Stack using Helm
      include_role:
        name: elk

    - name: Deploy Grafana using Helm
      include_role:
        name: grafana

- name: Configure VM for Nexus and Commvault (Docker-based)
  hosts: vm
  become: true
  tasks:
    - name: Install Docker on VM
      apt:
        name: docker.io
        state: present

    - name: Start Nexus Repository container
      include_role:
        name: nexus

    - name: Start Commvault container
      include_role:
        name: commvault
