ingress_nginx_namespace: ingress-nginx
ingress_nginx_release_name: ingress-nginx
ingress_nginx_helm_repo: https://kubernetes.github.io/ingress-nginx
ingress_nginx_chart_version: "4.12.1"
ingress_nginx_values:
  controller:
    publishService:
      enabled: true
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
