---
- name: Start Commvault container
  docker_container:
    name: commvault
    image: commvaultofficial/commvault
    state: started
    restart_policy: always
    published_ports:
      - "8400:8400"
      - "443:443"
