- name: Create Docker network for SonarQube
  community.docker.docker_network:
    name: sonarqube_network
    driver: bridge
    state: present

- name: Network sonarqube role completed
  ansible.builtin.meta: flush_handlers
