elk_namespace: elk
elk_release_name: elastic-stack
elk_helm_repo: https://helm.elastic.co
elk_chart_version: "8.12.0"
elk_values:
  ingress:
    enabled: true
    hosts:
      - host: elk.{{ cluster_domain }}
    tls:
      - secretName: elk-tls
        hosts:
          - elk.{{ cluster_domain }}
  replicas: 3
