- name: Create ELK namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ elk_namespace }}"
    state: present

- name: Add Elastic Helm repo
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: "{{ elk_helm_repo }}"

- name: Deploy Elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    chart_version: "{{ elk_chart_version }}"
    release_namespace: "{{ elk_namespace }}"
    values:
      replicas: "{{ elk_values.replicas }}"

- name: Deploy Kibana
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    chart_version: "{{ elk_chart_version }}"
    release_namespace: "{{ elk_namespace }}"
    values:
      ingress:
        enabled: true
        hosts:
          - host: kibana.{{ cluster_domain }}
        tls:
          - secretName: kibana-tls
            hosts:
              - kibana.{{ cluster_domain }}

- name: Deploy Logstash
  kubernetes.core.helm:
    name: logstash
    chart_ref: elastic/logstash
    chart_version: "{{ elk_chart_version }}"
    release_namespace: "{{ elk_namespace }}"
