- name: Ensure Docker is present for Nexus
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
