- name: Include Docker setup
  ansible.builtin.include_tasks: docker.yml

- name: Include Nexus setup
  ansible.builtin.include_tasks: nexus.yml

- name: Include HTTPS configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Configure UFW firewall
  ansible.builtin.include_tasks: ufw.yml
