- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure SSL directory exists
  ansible.builtin.file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Generate private key for NGINX TLS
  community.crypto.openssl_privatekey:
    path: /etc/nginx/ssl/nexus.key
    type: RSA
    size: 2048
    mode: "0600"

- name: Create CSR for NGINX TLS
  community.crypto.openssl_csr:
    path: /etc/nginx/ssl/nexus.csr
    privatekey_path: /etc/nginx/ssl/nexus.key
    common_name: "localhost"
    subject_alt_name:
      - "DNS:localhost"
    mode: "0644"

- name: Generate self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: /etc/nginx/ssl/nexus.crt
    csr_path: /etc/nginx/ssl/nexus.csr
    privatekey_path: /etc/nginx/ssl/nexus.key
    provider: selfsigned
    state: present
    mode: "0644"

- name: Deploy NGINX config for Nexus
  ansible.builtin.template:
    src: nginx-nexus.conf.j2
    dest: /etc/nginx/sites-available/nexus
    owner: root
    group: root
    mode: "0644"
  notify: Restart NGINX

- name: Enable Nexus site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/nexus
    dest: /etc/nginx/sites-enabled/nexus
    state: link
