- name: Ensure UFW is installed
  community.general.ufw:
    state: enabled

- name: Default deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow SSH, HTTP, HTTPS, Nexus registry
  community.general.ufw:
    rule: allow
    port: "22,80,443,{{ nexus_repo_port }}"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
