- name: Create Jenkins namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ jenkins_namespace }}"
    state: present

- name: Add Jenkins Helm repo
  kubernetes.core.helm_repository:
    name: jenkinsci
    repo_url: "{{ jenkins_helm_repo }}"

- name: Deploy Jenkins via Helm
  kubernetes.core.helm:
    name: "{{ jenkins_release_name }}"
    chart_ref: jenkinsci/jenkins
    chart_version: "{{ jenkins_chart_version }}"
    release_namespace: "{{ jenkins_namespace }}"
    values: "{{ jenkins_values }}"
