- name: Ensure vm.max_map_count is set
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: true

- name: Install common tools
  ansible.builtin.apt:
    name:
      - curl
      - git
      - htop
      - unzip
      - net-tools
      - python3
      - python3-pip
      - libpq-dev
      - openjdk-17-jdk
    state: present
    update_cache: true

- name: Install Python dependencies
  ansible.builtin.pip:
    name:
      - psycopg2-binary
      - docker
      - requests-unixsocket
      - ansible
    state: present
    executable: pip3

- name: Ensure Python packages are installed
  ansible.builtin.command:
    cmd: "python3 -m pip show psycopg2-binary"
  register: pip_check
  changed_when: false
  failed_when: pip_check.rc != 0

- name: Config role completed
  ansible.builtin.meta: flush_handlers
