- name: Install Terraform prerequisites
  ansible.builtin.apt:
    name:
      - unzip
      - curl
    update_cache: true

- name: Download Terraform archive
  ansible.builtin.get_url:
    url: "{{ terraform_download_url }}"
    dest: "/tmp/terraform_{{ terraform_version }}.zip"
    mode: "0644"

- name: Unarchive Terraform binary
  ansible.builtin.unarchive:
    src: "/tmp/terraform_{{ terraform_version }}.zip"
    dest: "{{ terraform_install_dir }}"
    remote_src: true
    creates: "{{ terraform_install_dir }}/terraform"

- name: Remove Terraform archive
  ansible.builtin.file:
    path: "/tmp/terraform_{{ terraform_version }}.zip"
    state: absent

- name: Ensure Terraform binary is executable
  ansible.builtin.file:
    path: "{{ terraform_install_dir }}/terraform"
    mode: "0755"

- name: Validate Terraform installation
  ansible.builtin.command:
    cmd: terraform --version
  register: tf_check
  changed_when: false
  failed_when: tf_check.rc != 0

- name: Terraform role completed
  ansible.builtin.meta: flush_handlers
