- name: Install Ansible prerequisites
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl

- name: Add the official Ansible PPA
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present

- name: Validate Ansible installation
  ansible.builtin.command:
    cmd: ansible --version
  register: ansible_check
  changed_when: false
  failed_when: ansible_check.rc != 0

- name: Ansible role completed
  ansible.builtin.meta: flush_handlers
